### ISSUE TITLE
include graphics

### ISSUE THREAD

**Issue by kleinhansda** [nilsleiffischer/latex-flipbook#1]
Hey,

thanks for this nice extension!

I tried to include images with \labeledflipbookframe but it wont work (tif/jpg/png). Could you provide an example on how to do this? Or point to a program that allows conversion to pgf?

Best,

David

**Comment by nilsvu** [comment]
Hi @KleinhansDa, please take a look at the `README.md`. It gives an example how to include images. Basically, since LaTeX can't `input` images, you need to add the following:

```tex
\renewcommand{\inputflipbookframe}[3]{\includegraphics{#1#2.#3}}
```

**Comment by nilsvu** [comment]
I'm closing this issue. Please open another one if you have follow-up questions.
